schema = 3

[mod]
  [mod."github.com/urfave/cli/v3"]
    version = "v3.6.1"
    hash = "sha256-q1WeKEvWoSyA0Wcan+Edjm71e0/vnPmqVvlfjUix7+8="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20251113190631-e25ba8c21ef6"
    hash = "sha256-OMf/iT0ZMyCrVkOqYvLNIgIJYI8dgIiSNDWY2z1Kjng="
